/*
 * Language Strings - English Language
 * -=-=-=-=-=-=-ORIGINAL-=-=-=-=-=-=-
 */

// Answers for 8ball command.
module.exports.ballreplies = [
	"Everything is possible.",
	"Without a doubt!",
	"Don't ask me again! I'm a ball!",
	"Outlook not so good.",
	"Yes – definitely.",
	"Come back in 15 years.",
	"My sources say yes.",
	"Leave me alone! I don't know!",
	"Go ask your mother!",
	"Where are my fries? No answer for you!",
	"Probability - 15%.",
	"Yes, of course!",
	"Signs point to yes.",
	"Never!",
	"Try asking Akinator!",
	"Go ask Chuck Norris!",
	"Brilliant idea!",
	"Go ask aliens or something.",
	"Only when the clouds will be green.",
	"Please no questions.",
	"Don't do it.",
	"Go ask Yoda!",
	"Probability - 69%.",
	"Buy me a burger, then I'll tell you.",
	"Give me your real estate, then I'll tell you.",
	"Leave me alone! I'm dancing to hardbass!",
	"Good idea!",
	"No answers right now!",
	"Do I look like prophet? I don't know!",
	"Ask again later! I'll tell you.",
	"I'm thirsty, I'll answer you later.",
	"Reply hazy, try again.",
	"I don't know!",
	"Concentrate and ask again.",
	"Go away! I'm looking at memes!",
	"No",
	"Check back in 5 days. I might tell you.",
	"I don't know, I'm not a genie!",
	"You've got to ask yourself one question: \'Do I feel lucky?\'\nWell, do you?",
	"It is decidedly so.",
	"As I see it, yes.",
	"Not a very good idea.",
	"Come back in 2 years, I'll tell you.",
	"I won't be able to tell you today.",
	"Yes",
	"Do it tomorow!",
	"Very doubtful.",
	"My reply is no.",
	"Possibly.",
	"Go ask Darth Vader!",
	"Go away, It's not my job!",
	"Cannot predict now...",
	"Only when dogs will fly.",
	"Try it! Maybe you'll get lucky.",
	"I think you should do it.",
	"Make them offer they can't refuse.",
	"Outlook good.",
	"Maybe later.",
	"Signs point to no.",
	"OMG, YES!",
	"Most likely.",
	"Better not tell you now.",
	"The stars say no.",
	"Go ask your family.",
	"The stars say yes.",
	"I don't think that's possible.",
	"Probability - 100%.",
	"My sources say no.",
	"Ask me again later.",
	"Maybe someday it will happen.",
	"You may rely on it.",
	"IDK, You tell me.",
	"Do it now!",
	"Probability - 0%.",
	"Why are you asking me this?",
	"I'm not feeling good, ask me a bit later.",
	"I am not sure...",
	"Absolutely!",
	"IDK, Ask someone else.",
	"Leave me alone, I've got a headache!",
	"Go ask Obi-Wan Kenobi!",
	"You can't do that!",
	"Start right now!",
	"Do it.",
	"Don't count on it.",
	"Never do it.",
	"Are you crazy? Of course not!",
	"JUST DO IT!",
	"It is certain."
];

// Greetings.
module.exports.greetings = [
	"Greetings from Arabic speakers - مرحبا",
	"Greetings from Bengali speakers - নমস্কার",
	"Greetings from Bulgarian speakers - Здравейте",
	"Greetings from Chinese(Mandarin) speakers - 你好",
	"Greetings from Croatian speakers - Zdravo",
	"Greetings from Danish speakers - Hallo",
	"Greetings from Dutch speakers - Hallo",
	"Greetings from Estonian speakers - Tere",
	"Greetings from Finnish speakers - Moikka",
	"Greetings from French speakers - Bonjour",
	"Greetings from German speakers - Hallo",
	"Greetings from Greek speakers - Γειά σου",
	"Greetings from Hebrew speakers - הלו",
	"Greetings from Hindi speakers - नमस्ते",
	"Greetings from Hungarian speakers - Szevasz",
	"Greetings from Icelandic speakers - Halló",
	"Greetings from Indonesian speakers - Halo",
	"Greetings from Irish(Gaeilge) speakers - Dia dhuit",
	"Greetings from Italian speakers - Salve",
	"Greetings from Japanese speakers - こんにちは",
	"Greetings from Korean speakers - 여보세요",
	"Greetings from Latvian speakers - Sveiki",
	"Greetings from Lithuanian speakers - Sveiki",
	"Greetings from Luxembourgish speakers - Hallo",
	"Greetings from Norwegian speakers - Hallo",
	"Greetings from Polish speakers - Cześć",
	"Greetings from Portuguese speakers - Olá",
	"Greetings from Romanian speakers - Bună ziua",
	"Greetings from Russian speakers - Привет",
	"Greetings from Slovak speakers - Ahoj",
	"Greetings from Spanish speakers - Hola",
	"Greetings from Swedish speakers - Hallå",
	"Greetings from Thai speakers - สวัสดี",
	"Greetings from Turkish speakers - Merhaba",
	"Greetings from Vietnamese speakers - Xin chào",
	"Greetings from Zulu speakers - Sawubona"
];

module.exports.antiLangStrings = {
	warn: "%author% has been warned!",
	warnX: "This is warning %active% out of 3 in %hours% hours!",
	warnFinal: [
		"This is your final warning! The following violation will result in mute!",
		"This is your final warning! The following violation will result in tempban!",
		"This is your final warning! The following violation will result in permban!"
	],
	mute: "%author% has been temporarily muted!",
	muteDM: "You have been temporarily muted in %guild%!",
	kick: "%author% has been temporarily banned!",
	kickDM: "You have been temporarily banned from %guild%!",
	ban: "%author% has been permanently banned!",
	banDM: "You have been permanently banned from %guild%!"
};

module.exports.infractionStrings = {
	spam: "Message Spam",
	mention: "Mass Mention",
	invite: "Sending Invite Link",
	language: "Usage Of Bad Language",
	badName: "Usage Of Bad Name"
};

module.exports.antiSpamStrings = {
	warn: "%author% has been warned!",
	warnX: "This is warning %active% out of 3 in %hours% hours!",
	warnFinal: [
		"This is your final warning! The following violation will result in mute!",
		"This is your final warning! The following violation will result in tempban!",
		"This is your final warning! The following violation will result in permban!"
	],
	mute: "%author% has been temporarily muted!",
	muteDM: "You have been temporarily muted in %guild%!",
	kick: "%author% has been temporarily banned!",
	kickDM: "You have been temporarily banned from %guild%!",
	ban: "%author% has been permanently banned!",
	banDM: "You have been permanently banned from %guild%!"
};

module.exports.antiRaidStrings = {
	muted: "You are currently muted in this guild!",
	tempBan: "You are currently banned from this guild!",
	lockdownActive: "This guild is currently on lockdown and doesn't accept new members.\nPlease try again later."
};

module.exports.variousStrings = {
	question: "Question",
	answer: "Answer",
	providedBy: "Provided by %provider%",
	guild: "Guild",
	channel: "Channel",
	author: "Author",
	warnedUser: "Warned User",
	mutedUser: "Muted User",
	bannedUser: "Banned User",
	reason: "Reason",
	messageContent: "Message",
	logs: "Logs",
	id: "ID"
};

module.exports.errorStrings = {
	error: "Error",
	errorUnknown: "An unknown error occured while running command.\nDeveloper has been informed.\nI'm sorry for the inconvenience.",
	errorDev: "An error occured while running command.",
	noCommand: "No Command",
	noCommandText: "There is no command with name %commandName%!\nCheck __**//help**__ for more information.",
	maintenance: "Maintenance",
	maintenanceText: "Bot is currently down for maintenance!\nNo commands/requests are accepted right now!\nPlease try again later.",
	disabled: "Disabled Command",
	disabledText: "I'm sorry, but this command is currently disabled!",
	botOwner: "Owner Command",
	botOwnerText: "I'm sorry, but this command is intended only for bot owner.",
	guildOnly: "Guild Only Command",
	guildOnlyText: "I'm sorry, but I can't execute this command inside DMs!",
	dmOnly: "DM Only Command",
	dmOnlyText: "I'm sorry, but I can't execute this command inside guilds!",
	guildOwnerOnly: "Guild Owner Command",
	guildOwnerOnlyText: "I'm sorry, but this command is intended only for guild owner.",
	noPerms: "Insufficent Permissions",
	noPermsText: "I'm sorry, but you don't have required permissions, %author%!\nPlease check __**//perms**__ for more information.",
	noArgsProvided: "No Arguments",
	noArgsProvidedText: "I'm sorry, but you didn't provide any arguments!\nThe proper usage would be:\n__**%usage%**__",
	notEnoughArgs: "Not Enough Arguments",
	notEnoughArgsText: "I'm sorry, but you didn't provide enough arguments!\nThe proper usage would be:\n__**%usage%**__",
	cooldown: "Command On Cooldown",
	cooldownText: "%author%, please wait %timeLeft% seconds before reusing this command.\nThis message will disappear when the cooldown is over."
};
