/*
 * Language Strings - Latvian Language
 * Translated by: EEHoveckis | Last Edit: [28/04/2021]
 */

// Atbildes 8ball komandai.
module.exports.ballreplies = [
	"Viss ir iespējams.",
	"Bez šaubām!",
	"Pārstaj man prasīt! Es esmu bumba!",
	"Iznākums nebūs labs.",
	"Jā, noteikti.",
	"Iegriezies pēc 15 gadiem.",
	"Mani avoti saka jā.",
	"Liec mani mierā! Es nezinu!",
	"Aizej paprasi savai mammai!",
	"Kur ir mani frī kartupeļi? Neko tev neteikšu!",
	"Iespējamība - 15%.",
	"Jā, protams!",
	"Zīmes norāda uz jā.",
	"Nekad!",
	"Mēģini prasīt Akinātoram!",
	"Paprasi Čakam Norisam!",
	"Brīnišķīga ideja!",
	"Paprasi citplanētiešiem vai kādam citam.",
	"Tikai, kad mākoņi būs zaļi.",
	"Lūdzu, bez jautājumiem.",
	"Nedari to.",
	"Aizej paprasi Jodai!",
	"Iespējamība - 69%.",
	"Nopērc man burgeru, tad es tev pateikšu.",
	"Atdot man savus īpašumus, tad es tev pateikšu.",
	"Liec mani mierā! Es dejoju pie hardbasa!",
	"Laba ideja!",
	"Šobrīd atbildes nav!",
	"Vai es izskatos pēc pareģa? Es nezinu!",
	"Uzprasi man vēlāk! Tad es tev pateikšu.",
	"Esmu izslāpis, es tev atbildēšu vēlāk.",
	"Atbilde miglaina, mēģini vēlreiz.",
	"Es nezinu!",
	"Koncentrējies un prasi vēlreiz.",
	"Ej prom! Es skatos uz mēmiem!",
	"Nē",
	"Atnāc pēc 5 dienām. Es varbūt tev pateikšu.",
	"Es nezinu, es neesmu džins!",
	"Tev jāuzprasa sev jautājums: \'Vai es jūtos veiksmīgs?\'\nNu, vai tu jūties?",
	"Tas ir neapšaubāmi.",
	"Man izskatās, ka jā.",
	"Ne tik laba ideja.",
	"Atnāc pēc 2 gadiem, tad es tev pateikšu.",
	"To es tev nevarēšu šodien pateikt.",
	"Jā",
	"Dari to rīt!",
	"Diezgan apšaubāmi.",
	"Mana atbilde ir nē.",
	"Iespējams.",
	"Aizej uzprasi Dārtam Vaderam!",
	"Ej prom, tas nav mans darbs!",
	"Nevaru šobrīd paredzēt...",
	"Tikai, kad suņi sāks lidot.",
	"Pamēģini! Varbūt tev paveiksies.",
	"Es domāju tev vajadzētu to darīt.",
	"Veic viņiem piedāvājumu no kura viņi nevarēs atteikties.",
	"Iznākums labs.",
	"Varbūt vēlāk.",
	"Zīmes norāda uz nē.",
	"Ak Dievs! Jā!",
	"Visticamāk ka jā.",
	"Labāk būs tev nezināt.",
	"Zvaigznes saka nē.",
	"Aizej paprasi savai ģimenei.",
	"Zvaigznes saka jā.",
	"Nedomāju, ka tas ir iespējams.",
	"Iespējamība - 100%.",
	"Mani avoti saka nē.",
	"Uzprasi man vēlāk.",
	"Varbūt kādu dienu tas notiks.",
	"Tu vari uz to paļauties.",
	"Es nezinu, pasaki tu man.",
	"Dari to tagad!",
	"Iespējamība - 0%.",
	"Kāpēc tu man to prasi?",
	"Es nejūtos labi, uzprasi man mazliet vēlāk.",
	"Es neesmu pārliecināts...",
	"Protams!",
	"Es nezinu, uzprasi kādam citam.",
	"Liec mani mierā, man sāp galva!",
	"Aizej uzprasi Obi Vanam Kenobi!",
	"Tu to nevari darīt!",
	"Sāc jau tagad!",
	"Dari to.",
	"Nemaz neceri.",
	"Nekad to nedari.",
	"Vai tu esi traks? Protams, ka nē!",
	"DARI TO!",
	"Notekti."
];

// Sveicieni.
module.exports.greetings = [
	"Sveicieni no Arābu valodā runājošiem  - مرحبا",
	"Sveicieni no Bengāļu valodā runājošiem  - নমস্কার",
	"Sveicieni no Bulgāru valodā runājošiem  - Здравейте",
	"Sveicieni no Ķīniešu(Mandarīnu) runājošiem  - 你好",
	"Sveicieni no Horvātu valodā runājošiem  - Zdravo",
	"Sveicieni no Dāņu valodā runājošiem  - Hallo",
	"Sveicieni no Flāmu valodā runājošiem  - Hallo",
	"Sveicieni no Igauņu valodā runājošiem  - Tere",
	"Sveicieni no Somu valodā runājošiem  - Moikka",
	"Sveicieni no Franču valodā runājošiem  - Bonjour",
	"Sveicieni no Vācu valodā runājošiem  - Hallo",
	"Sveicieni no Grieķu valodās runājošiem  - Γειά σου",
	"Sveicieni no Ebreju valodā runājošiem  - הלו",
	"Sveicieni no Hindi valodā runājošiem  - नमस्ते",
	"Sveicieni no Ungāru runājošiem  - Szevasz",
	"Sveicieni no Islandiešu valodā runājošiem  - Halló",
	"Sveicieni no Indonēziešu valodā runājošiem  - Halo",
	"Sveicieni no Īru(Gaeilge) valodā runājošiem  - Dia dhuit",
	"Sveicieni no Itāļu valodā runājošiem  - Salve",
	"Sveicieni no Japāņu valodā runājošiem  - こんにちは",
	"Sveicieni no Korejiešu valodā runājošiem  - 여보세요",
	"Sveicieni no Latviešu valodā runājošiem  - Sveiki",
	"Sveicieni no Lietuviešu valodā runājošiem  - Sveiki",
	"Sveicieni no Luksemburgiešu valodā runājošiem  - Hallo",
	"Sveicieni no Norwēģu valodā runājošiem  - Hallo",
	"Sveicieni no Poļu valodā runājošiem  - Cześć",
	"Sveicieni no Portugāļu valodā runājošiem  - Olá",
	"Sveicieni no Rumāņu valodā runājošiem  - Bună ziua",
	"Sveicieni no Krievu valodā runājošiem  - Привет",
	"Sveicieni no Slovāku valodā runājošiem  - Ahoj",
	"Sveicieni no Spāņu valodā runājošiem  - Hola",
	"Sveicieni no Zviedru valodā runājošiem  - Hallå",
	"Sveicieni no Thai valodā runājošiem  - สวัสดี",
	"Sveicieni no Turku valodā runājošiem  - Merhaba",
	"Sveicieni no Vjetnamiešu valodā runājošiem  - Xin chào",
	"Sveicieni no Zulu valodā runājošiem  - Sawubona"
];

module.exports.antiLangStrings = {
	warn: "%author% tika brīdināts!",
	warnX: "Šis ir brīdinājums %active% no 3, %hours% stundu laikā!",
	warnFinal: [
		"Šis ir jūsu pēdējais brīdinājums! Vēl viens pārkāpums, un jūs tiksiet apklusināts!",
		"Šis ir jūsu pēdējais brīdinājums! Vēl viens pārkāpums, un jūs tiksiet izmests uz laiku!",
		"Šis ir jūsu pēdējais brīdinājums! Vēl viens pārkāpums, un jūs tiksiet izmests uz visiem laikiem!"
	],
	mute: "%author% tika uz laiku apklusināts!",
	muteDM: "Jūs tikāt apklusināts ģildē %guild%!",
	kick: "%author% tika uz laiku izmests!",
	kickDM: "Jūs tikāt uz laiku izmests no ģildes %guild%!",
	ban: "%author% tika uz visiem laikiem izmests!",
	banDM: "Jūs tikāt uz visiem laikiem izmests no ģildes %guild%!"
};

module.exports.infractionStrings = {
	spam: "Pārmērīgs Surogātpasts",
	mention: "Masveida Pieminēšana",
	invite: "Ielūguma Saišu Sūtīšana",
	language: "Sliktas Valodas Lietošana",
	badName: "Slikta Lietotājvārda Izmantošana",
	zalgo: "Zalgo Teksta Lietošana",
	emoji: "Masveida Emoji Lietošana",
	caps: "Lielo Burtu Pārmērīga Lietošana",
	spoilers: "Spoilera Tagu Pārmērīga Izmantošana"
};

module.exports.antiSpamStrings = {
	warn: "%author% tika brīdināts!",
	warnX: "Šis ir brīdinājums %active% no 3, %hours% stundu laikā!",
	warnFinal: [
		"Šis ir jūsu pēdējais brīdinājums! Vēl viens pārkāpums, un jūs tiksiet apklusināts!",
		"Šis ir jūsu pēdējais brīdinājums! Vēl viens pārkāpums, un jūs tiksiet izmests uz laiku!",
		"Šis ir jūsu pēdējais brīdinājums! Vēl viens pārkāpums, un jūs tiksiet izmests uz visiem laikiem!"
	],
	mute: "%author% tika uz laiku apklusināts!",
	muteDM: "Jūs tikāt uz laiku apklusināts ģildē %guild%!",
	kick: "%author% tika uz laiku izmests!",
	kickDM: "Jūs tikāt uz laiku izmests no ģildes %guild%!",
	ban: "%author% tika uz visiem laikiem izmests!",
	banDM: "Jūs tikāt uz visiem laikiem izmests no ģildes %guild%!"
};

module.exports.antiRaidStrings = {
	muted: "Jūs šobrīd esat apklusināts šijā ģildē!",
	tempBan: "Jūs esat uz laiku izmests no šīs ģildes!",
	lockdownActive: "Šī ģilde šobrīd ir slēgta un nepieņem jaunus biedrus.\nLūdzu mēģiniet vēlreiz vēlāk."
};

module.exports.variousStrings = {
	question: "Jautājums",
	answer: "Atbilde",
	providedBy: "Atbildi nodrošina %provider%",
	guild: "Ģilde",
	channel: "Kanāls",
	author: "Autors",
	warnedUser: "Brīdinātais lietotājs",
	mutedUser: "Apklusinātais lietotājs",
	bannedUser: "Izmestais lietotājs",
	reason: "Iemesls",
	messageContent: "Nosūtītā ziņa",
	logs: "Ieraksti",
	id: "ID",
	coins: "Monētas",
	xp: "Pieredze"
};

module.exports.errorStrings = {
	error: "Kļūda",
	errorUnknown: "Komandas izpildes laikā, notika kļūda.\nIzstrādātājs ir informēts.\nEs atvainojos par sagādātajām neērtībām.",
	errorDev: "Komandas izpildes laikā, notika kļūda.",
	noCommand: "Neeksistējoša komanda",
	noCommandText: "Komanda ar nosaukumu %commandName% nepastāv!\nApskatiet __**//help**__, papildus informācijai.",
	maintenance: "Uzturēšanas Režīms",
	maintenanceText: "Bots šobrīd atrodas uzturēšanas režīmā!\nKomandas/pieprasījumi šobrīd netiek pieņemti!\nLūdzu mēģiniet vēlāk vēlreiz.",
	disabled: "Atspējota Komanda",
	disabledText: "Es atvainojos, bet šī komanda nav šobrīd pieejama.",
	botOwner: "Izstrādātāja Komanda",
	botOwnerText: "Es atvainojos, bet šī komanda ir paredzēta tikai izstrādātājam.",
	guildOnly: "Komanda Tikai Giļdēm",
	guildOnlyText: "Es atvainojos, bet es nevaru izpildīt šo komandu privātajā sarakstē.",
	dmOnly: "Privātās Sarakstes Komanda",
	dmOnlyText: "Es atvainojos, bet es nevaru izpildīt šo komandu ģildē.",
	guildOwnerOnly: "Ģildes Īpašnieka Komanda",
	guildOwnerOnlyText: "Es atvainojos, bet šī komanda ir paredzēta tikai ģildes īpašniekam.",
	noPerms: "Nepietiekamas Atļaujas",
	noPermsText: "Es atvainojos, bet jums nav nepieciešamās atļaujas, %author%!\nApskatiet __**//perms**__ papildus informācijai.",
	noArgsProvided: "Nav Argumentu",
	noArgsProvidedText: "Es atvainojos, bet jūs nepievienojāt nevienu argumentu!\nPareiza komandas lietošana būtu:\n__**%usage%**__",
	notEnoughArgs: "Nepietiekams Argumentu Skaits",
	notEnoughArgsText: "Es atvainojos, bet jūs pievienojāt nepietiekamu argumentu skaitu!\nPareiza komandas lietošana būtu:\n__**%usage%**__",
	cooldown: "Komanda Atjaunojas",
	cooldownText: "%author%, lūdzu uzgaidiet %timeLeft% sekundes līdz atkal lietot šo komandu.\nŠī ziņa izdzēsīsies, kad gaidīšanas laiks beigsies."
};
