import type { NextPage } from "next";
import Head from "next/head";
import Router from "next/router";
import Script from "next/script";
import { useEffect, useState } from "react";
import DashboardComponent from "../../components/defensie/DashboardComponent";
import HomeContainer from "../../components/defensie/HomeContainer";
import ListComponent from "../../components/defensie/ListComponent";
import SideNav from "../../components/defensie/SideNav";
import Footer from "../../components/Main/Footer";
import styles from "../../styles/Home.module.css";
import { CheckLoggedIn } from "../../util/authentication";
import { GetDarkMode } from "../../util/darkmode";

const Home: NextPage = () => {
  const [darkmode, setDarkmode] = useState<boolean>(false);
  const [isLoaded, setLoading] = useState<boolean>(true);

  useEffect(() => {
    if (CheckLoggedIn()) {
      if (GetDarkMode()) setDarkmode(true);
    } else Router.push("/login");

    setLoading(false);
  }, []);

  return !isLoaded ? (
    <div className={`${styles.container} ${darkmode ? styles.dark_mode : ""}`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://kit.fontawesome.com/82faba1ef6.js"></Script>
      <SideNav />
      <HomeContainer className={styles.home_container}>
        <DashboardComponent />
        <ListComponent />
        <Footer />
      </HomeContainer>
    </div>
  ) : (
    <div>Loading</div>
  );
};

export default Home;
